### ISSUE TITLE
Dapp doesn't match the latest robonomics-js

### ISSUE THREAD

**Issue by Vourhey** [airalab/vue-dapp-robonomics-template#2]
The error is `robonomics.getAsk is not a function`

![photo_2018-11-06_12-24-09](https://user-images.githubusercontent.com/709124/48054730-fed1d380-e1be-11e8-8cac-93abc11cb163.jpg)

**Comment by vol4tim** [comment]
https://github.com/airalab/vue-dapp-robonomics-template/blob/3850164795e21968f476bc8081203ef72321ca23/template/src/components/Order.vue#L196-L198
